[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "moo"
version = "0.1.0"
description = "Python modeling and AD-based code generation environment for MOO"
requires-python = ">=3.10"
dependencies = [
    "matplotlib",
    "pandas",
    "numpy",
]

[tool.setuptools]
package-dir = {"" = "python"}

[tool.setuptools.packages.find]
where = ["python"]
