/* Simulation code for include_test generated by the OpenModelica Compiler v1.26.0-dev-51-g1b6c45e882-cmake. */
#if !defined(include_test__MODEL_H)
#define include_test__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"
#include "simulation/solver/synchronous.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "include_test_functions.h"


extern void include_test_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void include_test_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int include_test_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int include_test_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int include_test_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int include_test_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int include_test_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int include_test_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int include_test_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int include_test_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int include_test_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int include_test_checkForAsserts(DATA *data, threadData_t *threadData);
extern int include_test_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int include_test_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int include_test_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* include_test_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* include_test_relationDescription(int i);
extern void include_test_function_initSample(DATA *data, threadData_t *threadData);
extern int include_test_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int include_test_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int include_test_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int include_test_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int include_test_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int include_test_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int include_test_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int include_test_functionJacG_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int include_test_functionJacA_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int include_test_functionJacB_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int include_test_functionJacC_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int include_test_functionJacD_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int include_test_functionJacF_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int include_test_functionJacH_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern const char* include_test_linear_model_frame(void);
extern const char* include_test_linear_model_datarecovery_frame(void);
extern int include_test_mayer(DATA* data, modelica_real** res, short *);
extern int include_test_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int include_test_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int include_test_setInputData(DATA *data, const modelica_boolean file);
extern int include_test_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void include_test_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void include_test_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int include_test_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void include_test_read_simulation_info(SIMULATION_INFO* simulationData);
extern void include_test_read_input_fmu(MODEL_DATA* modelData);
extern void include_test_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int include_test_inputNames(DATA* data, char ** names);
extern int include_test_dataReconciliationInputNames(DATA* data, char ** names);
extern int include_test_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int include_test_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int include_test_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int include_test_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "include_test_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(include_test__MODEL_H) */


