# Makefile generated by OpenModelica
# Platform: linux64

# Simulations use -O3 by default
CC=/usr/bin/cc
CXX=/usr/bin/c++
LINK=/usr/bin/cc -shared
EXEEXT=
DLLEXT=.so
CFLAGS_BASED_ON_INIT_FILE=
# define OMC_CFLAGS_OPTIMIZATION env variable to your desired optimization level to override this
OMC_CFLAGS_OPTIMIZATION=-Os
DEBUG_FLAGS=$(OMC_CFLAGS_OPTIMIZATION)
CFLAGS= $(CFLAGS_BASED_ON_INIT_FILE) $(DEBUG_FLAGS) -DOM_HAVE_PTHREADS -fPIC -DOM_HAVE_PTHREADS    
CPPFLAGS= -I"/home/linus/Projects/OpenModelica/build_cmake/install_cmake/bin/../include/omc/c" -I"/home/linus/Projects/OpenModelica/build_cmake/install_cmake/bin/../include/omc" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=include_test -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=0 -DOMC_NUM_NONLINEAR_SYSTEMS=0 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0
# define OMC_LDFLAGS_LINK_TYPE env variable to "static" to override this
OMC_LDFLAGS_LINK_TYPE=dynamic
RUNTIME_LIBS= -lSimulationRuntimeC -lOpenModelicaRuntimeC -lomcgc -lzlib -llapack -lblas -lm -ldl -lpthread -lgfortran -lstdc++ -rdynamic 
LDFLAGS=-L"/home/linus/Projects/OpenModelica/build_cmake/install_cmake/bin/../lib/x86_64-linux-gnu/omc" -L"/home/linus/Projects/OpenModelica/build_cmake/install_cmake/bin/../lib" -Wl,-rpath,"/home/linus/Projects/OpenModelica/build_cmake/install_cmake/bin/../lib/x86_64-linux-gnu/omc"  -Wl,-rpath,"/home/linus/Projects/OpenModelica/build_cmake/install_cmake/bin/../lib"   $(RUNTIME_LIBS) 
DIREXTRA=-L"/home/linus/Projects/Optimization/src/modelica/example"
MAINFILE=include_test.c
MAINOBJ=include_test.o
CFILES=include_test_functions.c include_test_records.c \
include_test_01exo.c include_test_02nls.c include_test_03lsy.c include_test_04set.c include_test_05evt.c include_test_06inz.c include_test_07dly.c \
include_test_08bnd.c include_test_09alg.c include_test_10asr.c include_test_11mix.c include_test_12jac.c include_test_13opt.c include_test_14lnz.c \
include_test_15syn.c include_test_16dae.c include_test_17inl.c include_test_18spd.c 

OFILES=$(CFILES:.c=.o)
GENERATEDFILES=$(MAINFILE) include_test.makefile include_test_literals.h include_test_functions.h $(CFILES)

.PHONY: omc_main_target clean bundle

# This is to make sure that include_test_*.c are always compiled.
.PHONY: $(CFILES)

omc_main_target: $(MAINOBJ) include_test_functions.h include_test_literals.h $(OFILES)
	$(CC) -I. -o include_test$(EXEEXT) $(MAINOBJ) $(OFILES) $(DIREXTRA)   $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)

omc_dll_target: $(MAINOBJ) include_test_functions.h include_test_literals.h $(OFILES)
	$(CC) -DOMC_DLL_MAIN_DEFINE -o $(MAINOBJ) -c $(MAINFILE) $(DIREXTRA)   $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
	$(CC) -shared -I. -o include_test$(DLLEXT) $(MAINOBJ) $(OFILES) $(DIREXTRA)   $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)

clean:
	@rm -f include_test_records.o $(MAINOBJ)

bundle:
	@tar -cvf include_test_Files.tar $(GENERATEDFILES)