/* Additional record code for include_test generated by the OpenModelica Compiler v1.26.0-dev-108-gda288b257f-cmake. */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "include_test_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

