// SPDX-License-Identifier: LGPL-3.0-or-later
#include "codegen.h"

#include "detail/function_core.h"
#include "detail/matrix_ops.h"
#include "detail/mapping.h"
#include "detail/node.h"

#include <algorithm>
#include <cmath>
#include <iomanip>
#include <limits>
#include <sstream>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

namespace ad {
namespace {

using detail::FunctionCore;
using detail::ScalarNode;
using detail::VecNode;

class Writer {
public:
    void line(const std::string &text = std::string()) {
        for (int i = 0; i < indent_; ++i) {
            out_ << "    ";
        }
        out_ << text << '\n';
    }

    void indent() { ++indent_; }
    void dedent() {
        if (indent_ == 0) {
            throw std::runtime_error("internal codegen indentation underflow");
        }
        --indent_;
    }

    std::string str() const { return out_.str(); }

private:
    std::ostringstream out_;
    int indent_ = 0;
};

struct FunctionEntry {
    std::shared_ptr<const FunctionCore> core;
    std::string helper_name;
};

bool is_c_identifier(const std::string &name) {
    if (name.empty()) {
        return false;
    }
    const auto is_alpha = [](char c) {
        return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == '_';
    };
    const auto is_alnum = [&](char c) {
        return is_alpha(c) || (c >= '0' && c <= '9');
    };
    if (!is_alpha(name[0])) {
        return false;
    }
    for (char c : name) {
        if (!is_alnum(c)) {
            return false;
        }
    }
    return true;
}

std::string number_literal(double value) {
    if (std::isnan(value)) {
        return "NAN";
    }
    if (std::isinf(value)) {
        return value > 0 ? "INFINITY" : "(-INFINITY)";
    }
    std::ostringstream out;
    out << std::setprecision(17) << value;
    std::string text = out.str();
    if (text.find_first_of(".eE") == std::string::npos) {
        text += ".0";
    }
    return text;
}

std::string int_array_literal(const std::vector<int> &values) {
    std::ostringstream out;
    out << "{";
    for (std::size_t i = 0; i < values.size(); ++i) {
        if (i != 0) {
            out << ", ";
        }
        out << values[i];
    }
    out << "}";
    return out.str();
}

std::string double_array_literal(const std::vector<double> &values) {
    std::ostringstream out;
    out << "{";
    for (std::size_t i = 0; i < values.size(); ++i) {
        if (i != 0) {
            out << ", ";
        }
        out << number_literal(values[i]);
    }
    out << "}";
    return out.str();
}

class Codegen {
public:
    Codegen(const Function &function, CodegenOptions options)
        : root_(detail::function_core(function)),
          options_(std::move(options)) {
        if (!root_) {
            throw std::runtime_error("cannot generate code for invalid function");
        }
        if (!is_c_identifier(options_.function_name)) {
            throw std::runtime_error("CodegenOptions::function_name must be a valid C identifier");
        }
        if (options_.scalar_type.empty()) {
            throw std::runtime_error("CodegenOptions::scalar_type must not be empty");
        }
        if (!is_c_identifier(options_.linear_solve_function)) {
            throw std::runtime_error("CodegenOptions::linear_solve_function must be a valid C identifier");
        }
        collect_function(root_);
    }

    CodegenResult generate() {
        Writer w;
        w.line("/* Generated by MOO AD baseline C codegen. */");
        w.line("#include <math.h>");
        w.line("#ifdef __cplusplus");
        w.line("extern \"C\" {");
        w.line("#endif");
        w.line("typedef struct MOOAdLinearSolveProblem {");
        w.line("    int size;");
        w.line("    int layout;");
        w.line("    int transpose;");
        w.line("    const double* matrix;");
        w.line("    const double* rhs;");
        w.line("    double* solution;");
        w.line("} MOOAdLinearSolveProblem;");
        w.line("extern int " + options_.linear_solve_function + "(const MOOAdLinearSolveProblem* problem);");
        w.line("#ifdef __cplusplus");
        w.line("}");
        w.line("#endif");
        w.line();
        for (const FunctionEntry &entry : functions_) {
            w.line("static void " + entry.helper_name + "(const " + options_.scalar_type + "* in, const " + options_.scalar_type + "* p, " + options_.scalar_type + "* out);");
        }
        w.line();
        for (const FunctionEntry &entry : functions_) {
            emit_helper(w, *entry.core, entry.helper_name);
            w.line();
        }
        w.line("void " + options_.function_name + "(const " + options_.scalar_type + "* in, const " + options_.scalar_type + "* p, " + options_.scalar_type + "* out) {");
        w.indent();
        w.line(function_name(root_.get()) + "(in, p, out);");
        w.dedent();
        w.line("}");
        w.line();
        w.line("int " + options_.function_name + "_input_size(void) { return " + std::to_string(root_->info.input_size) + "; }");
        w.line("int " + options_.function_name + "_parameter_size(void) { return " + std::to_string(root_->parameters.size()) + "; }");
        w.line("int " + options_.function_name + "_output_size(void) { return " + std::to_string(root_->info.output_size) + "; }");
        if (options_.emit_sparsity_metadata) {
            emit_sparsity_metadata(w);
        }

        CodegenResult result;
        result.source = w.str();
        result.entry_name = options_.function_name;
        result.input_size = root_->info.input_size;
        result.parameter_size = root_->parameters.size();
        result.output_size = root_->info.output_size;
        return result;
    }

private:
    struct EmitContext {
        Codegen *owner = nullptr;
        Writer *writer = nullptr;
        const FunctionCore *core = nullptr;
        std::unordered_map<VarId, int> var_index;
        std::unordered_map<ParamId, int> param_index;
        int temp_counter = 0;
        int const_counter = 0;

        std::string new_temp(const std::string &prefix) {
            return prefix + std::to_string(temp_counter++);
        }

        std::string new_const(const std::string &prefix) {
            return prefix + std::to_string(const_counter++);
        }
    };

    std::shared_ptr<const FunctionCore> root_;
    CodegenOptions options_;
    std::vector<FunctionEntry> functions_;
    std::unordered_map<const FunctionCore *, int> function_indices_;

    std::string function_name(const FunctionCore *core) const {
        const auto found = function_indices_.find(core);
        if (found == function_indices_.end()) {
            throw std::runtime_error("internal codegen missing function helper");
        }
        return functions_[static_cast<std::size_t>(found->second)].helper_name;
    }

    void collect_function(const std::shared_ptr<const FunctionCore> &core) {
        if (!core) {
            throw std::runtime_error("cannot collect invalid function core for codegen");
        }
        if (function_indices_.find(core.get()) != function_indices_.end()) {
            return;
        }
        const int index = static_cast<int>(functions_.size());
        function_indices_[core.get()] = index;
        functions_.push_back(FunctionEntry{core, options_.function_name + "_core_" + std::to_string(index)});
        collect_vec(detail::vec_node(core->output));
    }

    void collect_scalar(const std::shared_ptr<const ScalarNode> &node) {
        if (!node) {
            return;
        }
        collect_vec(node->vec);
        collect_vec(node->vec_lhs);
        collect_vec(node->vec_rhs);
        collect_scalar(node->lhs);
        collect_scalar(node->rhs);
    }

    void collect_vec(const std::shared_ptr<const VecNode> &node) {
        if (!node) {
            return;
        }
        collect_scalar(node->scale);
        collect_vec(node->lhs);
        collect_vec(node->rhs);
        for (const auto &element : node->elements) {
            collect_scalar(element);
        }
        for (const auto &argument : node->arguments) {
            collect_vec(argument);
        }
        for (const auto &binding : node->mapped_bindings) {
            collect_vec(binding.source);
        }
        if (node->kind == GraphNodeKind::FunctionCall || node->kind == GraphNodeKind::MappedFunctionCall || node->kind == GraphNodeKind::MapAccumCall) {
            collect_function(node->function);
        }
    }

    EmitContext make_context(Writer &w, const FunctionCore &core) {
        EmitContext context;
        context.owner = this;
        context.writer = &w;
        context.core = &core;
        for (int i = 0; i < core.input_vars.size(); ++i) {
            context.var_index[core.input_vars[i].id()] = i;
        }
        for (int i = 0; i < core.parameters.size(); ++i) {
            context.param_index[core.parameters[i].id()] = i;
        }
        return context;
    }

    void emit_helper(Writer &w, const FunctionCore &core, const std::string &name) {
        w.line("static void " + name + "(const " + options_.scalar_type + "* in, const " + options_.scalar_type + "* p, " + options_.scalar_type + "* out) {");
        w.indent();
        EmitContext context = make_context(w, core);
        emit_vec_to(context, detail::vec_node(core.output), "out");
        w.dedent();
        w.line("}");
    }

    std::string declare_array(EmitContext &context, int size, const std::string &prefix) {
        if (size <= 0) {
            return "out";
        }
        const std::string name = context.new_temp(prefix);
        context.writer->line(options_.scalar_type + " " + name + "[" + std::to_string(size) + "];");
        return name;
    }

    std::string declare_int_array(EmitContext &context, const std::vector<int> &values, const std::string &prefix) {
        const std::string name = context.new_const(prefix);
        context.writer->line("static const int " + name + "[" + std::to_string(values.size()) + "] = " + int_array_literal(values) + ";");
        return name;
    }

    std::string declare_scalar_array(EmitContext &context, const std::vector<double> &values, const std::string &prefix) {
        const std::string name = context.new_const(prefix);
        context.writer->line("static const " + options_.scalar_type + " " + name + "[" + std::to_string(values.size()) + "] = " + double_array_literal(values) + ";");
        return name;
    }

    std::string emit_vec_temp(EmitContext &context, const std::shared_ptr<const VecNode> &node, const std::string &prefix) {
        const std::string temp = declare_array(context, node ? node->size : 0, prefix);
        emit_vec_to(context, node, temp);
        return temp;
    }

    int require_var_index(EmitContext &context, const Var &var) {
        const auto found = context.var_index.find(var.id());
        if (found == context.var_index.end()) {
            throw std::runtime_error("codegen variable is not in function input layout");
        }
        return found->second;
    }

    int require_param_index(EmitContext &context, const Param &param) {
        const auto found = context.param_index.find(param.id());
        if (found == context.param_index.end()) {
            throw std::runtime_error("codegen parameter is not in function parameter layout");
        }
        return found->second;
    }

    std::string emit_scalar_expr(EmitContext &context, const std::shared_ptr<const ScalarNode> &node) {
        if (!node) {
            throw std::runtime_error("cannot generate code for invalid scalar node");
        }
        switch (node->kind) {
            case GraphNodeKind::ScalarConstant:
                return number_literal(node->value);
            case GraphNodeKind::ScalarVariable:
                return "in[" + std::to_string(require_var_index(context, node->var)) + "]";
            case GraphNodeKind::ScalarParameter:
                return "p[" + std::to_string(require_param_index(context, node->param)) + "]";
            case GraphNodeKind::ScalarUnary: {
                const std::string arg = emit_scalar_expr(context, node->lhs);
                switch (node->unary) {
                    case detail::ScalarUnaryOp::Neg:
                        return "(-(" + arg + "))";
                    case detail::ScalarUnaryOp::Sin:
                        return "sin(" + arg + ")";
                    case detail::ScalarUnaryOp::Cos:
                        return "cos(" + arg + ")";
                    case detail::ScalarUnaryOp::Tan:
                        return "tan(" + arg + ")";
                    case detail::ScalarUnaryOp::Exp:
                        return "exp(" + arg + ")";
                    case detail::ScalarUnaryOp::Log:
                        return "log(" + arg + ")";
                    case detail::ScalarUnaryOp::PowConst:
                        return "pow(" + arg + ", " + number_literal(node->value) + ")";
                    case detail::ScalarUnaryOp::Abs:
                        return "fabs(" + arg + ")";
                    case detail::ScalarUnaryOp::Sqrt:
                        return "sqrt(" + arg + ")";
                    case detail::ScalarUnaryOp::Asin:
                        return "asin(" + arg + ")";
                    case detail::ScalarUnaryOp::Acos:
                        return "acos(" + arg + ")";
                    case detail::ScalarUnaryOp::Atan:
                        return "atan(" + arg + ")";
                    case detail::ScalarUnaryOp::Sinh:
                        return "sinh(" + arg + ")";
                    case detail::ScalarUnaryOp::Cosh:
                        return "cosh(" + arg + ")";
                    case detail::ScalarUnaryOp::Tanh:
                        return "tanh(" + arg + ")";
                    case detail::ScalarUnaryOp::Log10:
                        return "log10(" + arg + ")";
                    case detail::ScalarUnaryOp::Sigmoid:
                        return "(1.0 / (1.0 + exp(-(" + arg + "))))";
                }
                break;
            }
            case GraphNodeKind::ScalarBinary: {
                const std::string lhs = emit_scalar_expr(context, node->lhs);
                const std::string rhs = emit_scalar_expr(context, node->rhs);
                switch (node->binary) {
                    case detail::ScalarBinaryOp::Add:
                        return "((" + lhs + ") + (" + rhs + "))";
                    case detail::ScalarBinaryOp::Sub:
                        return "((" + lhs + ") - (" + rhs + "))";
                    case detail::ScalarBinaryOp::Mul:
                        return "((" + lhs + ") * (" + rhs + "))";
                    case detail::ScalarBinaryOp::Div:
                        return "((" + lhs + ") / (" + rhs + "))";
                    case detail::ScalarBinaryOp::Pow:
                        return "pow(" + lhs + ", " + rhs + ")";
                    case detail::ScalarBinaryOp::Min:
                        return "fmin(" + lhs + ", " + rhs + ")";
                    case detail::ScalarBinaryOp::Max:
                        return "fmax(" + lhs + ", " + rhs + ")";
                }
                break;
            }
            case GraphNodeKind::VectorElement: {
                const std::string vec = emit_vec_temp(context, node->vec, "v");
                return vec + "[" + std::to_string(node->index) + "]";
            }
            case GraphNodeKind::Sum: {
                const std::string vec = emit_vec_temp(context, node->vec, "v");
                const std::string sum = context.new_temp("s");
                context.writer->line(options_.scalar_type + " " + sum + " = 0.0;");
                context.writer->line("for (int i = 0; i < " + std::to_string(node->vec->size) + "; ++i) {");
                context.writer->indent();
                context.writer->line(sum + " += " + vec + "[i];");
                context.writer->dedent();
                context.writer->line("}");
                return sum;
            }
            case GraphNodeKind::Dot: {
                const std::string lhs = emit_vec_temp(context, node->vec_lhs, "vl");
                const std::string rhs = emit_vec_temp(context, node->vec_rhs, "vr");
                const std::string dot = context.new_temp("d");
                context.writer->line(options_.scalar_type + " " + dot + " = 0.0;");
                context.writer->line("for (int i = 0; i < " + std::to_string(node->vec_lhs->size) + "; ++i) {");
                context.writer->indent();
                context.writer->line(dot + " += " + lhs + "[i] * " + rhs + "[i];");
                context.writer->dedent();
                context.writer->line("}");
                return dot;
            }
            default:
                break;
        }
        throw std::runtime_error("unsupported scalar node in codegen");
    }

    std::string emit_vec_unary_expr(detail::VecUnaryOp op, const std::string &arg) const {
        switch (op) {
            case detail::VecUnaryOp::Neg:
                return "(-(" + arg + "))";
            case detail::VecUnaryOp::Sin:
                return "sin(" + arg + ")";
            case detail::VecUnaryOp::Cos:
                return "cos(" + arg + ")";
            case detail::VecUnaryOp::Tan:
                return "tan(" + arg + ")";
            case detail::VecUnaryOp::Exp:
                return "exp(" + arg + ")";
            case detail::VecUnaryOp::Log:
                return "log(" + arg + ")";
            case detail::VecUnaryOp::Sigmoid:
                return "(1.0 / (1.0 + exp(-(" + arg + "))))";
            case detail::VecUnaryOp::Abs:
                return "fabs(" + arg + ")";
            case detail::VecUnaryOp::Sqrt:
                return "sqrt(" + arg + ")";
            case detail::VecUnaryOp::Asin:
                return "asin(" + arg + ")";
            case detail::VecUnaryOp::Acos:
                return "acos(" + arg + ")";
            case detail::VecUnaryOp::Atan:
                return "atan(" + arg + ")";
            case detail::VecUnaryOp::Sinh:
                return "sinh(" + arg + ")";
            case detail::VecUnaryOp::Cosh:
                return "cosh(" + arg + ")";
            case detail::VecUnaryOp::Tanh:
                return "tanh(" + arg + ")";
            case detail::VecUnaryOp::Log10:
                return "log10(" + arg + ")";
        }
        throw std::runtime_error("unsupported vector unary op in codegen");
    }

    std::string emit_vec_binary_expr(detail::VecBinaryOp op, const std::string &lhs, const std::string &rhs) const {
        switch (op) {
            case detail::VecBinaryOp::Add:
                return "((" + lhs + ") + (" + rhs + "))";
            case detail::VecBinaryOp::Sub:
                return "((" + lhs + ") - (" + rhs + "))";
            case detail::VecBinaryOp::Mul:
                return "((" + lhs + ") * (" + rhs + "))";
            case detail::VecBinaryOp::Div:
                return "((" + lhs + ") / (" + rhs + "))";
            case detail::VecBinaryOp::Pow:
                return "pow(" + lhs + ", " + rhs + ")";
            case detail::VecBinaryOp::Min:
                return "fmin(" + lhs + ", " + rhs + ")";
            case detail::VecBinaryOp::Max:
                return "fmax(" + lhs + ", " + rhs + ")";
        }
        throw std::runtime_error("unsupported vector binary op in codegen");
    }

    void emit_vec_to(EmitContext &context, const std::shared_ptr<const VecNode> &node, const std::string &out) {
        if (!node) {
            throw std::runtime_error("cannot generate code for invalid vector node");
        }
        switch (node->kind) {
            case GraphNodeKind::VectorVariable:
                for (int i = 0; i < node->size; ++i) {
                    context.writer->line(out + "[" + std::to_string(i) + "] = in[" + std::to_string(require_var_index(context, node->vars[static_cast<std::size_t>(i)])) + "];");
                }
                break;
            case GraphNodeKind::VectorParameter:
                for (int i = 0; i < node->size; ++i) {
                    context.writer->line(out + "[" + std::to_string(i) + "] = p[" + std::to_string(require_param_index(context, node->params[static_cast<std::size_t>(i)])) + "];");
                }
                break;
            case GraphNodeKind::VectorConstant:
                for (int i = 0; i < node->size; ++i) {
                    context.writer->line(out + "[" + std::to_string(i) + "] = " + number_literal(node->constants[static_cast<std::size_t>(i)]) + ";");
                }
                break;
            case GraphNodeKind::VectorFromElements:
                for (int i = 0; i < node->size; ++i) {
                    context.writer->line(out + "[" + std::to_string(i) + "] = " + emit_scalar_expr(context, node->elements[static_cast<std::size_t>(i)]) + ";");
                }
                break;
            case GraphNodeKind::VectorUnary: {
                const std::string arg = emit_vec_temp(context, node->lhs, "u");
                for (int i = 0; i < node->size; ++i) {
                    context.writer->line(out + "[" + std::to_string(i) + "] = " + emit_vec_unary_expr(node->unary, arg + "[" + std::to_string(i) + "]") + ";");
                }
                break;
            }
            case GraphNodeKind::VectorBinary: {
                const std::string lhs = emit_vec_temp(context, node->lhs, "l");
                const std::string rhs = emit_vec_temp(context, node->rhs, "r");
                for (int i = 0; i < node->size; ++i) {
                    context.writer->line(out + "[" + std::to_string(i) + "] = " + emit_vec_binary_expr(node->binary, lhs + "[" + std::to_string(i) + "]", rhs + "[" + std::to_string(i) + "]") + ";");
                }
                break;
            }
            case GraphNodeKind::VectorScale: {
                const std::string scale = emit_scalar_expr(context, node->scale);
                const std::string arg = emit_vec_temp(context, node->lhs, "vs");
                for (int i = 0; i < node->size; ++i) {
                    context.writer->line(out + "[" + std::to_string(i) + "] = (" + scale + ") * " + arg + "[" + std::to_string(i) + "];");
                }
                break;
            }
            case GraphNodeKind::DenseMatVec: {
                const std::string arg = emit_vec_temp(context, node->lhs, "dmv");
                for (int row = 0; row < node->dense.rows; ++row) {
                    context.writer->line(out + "[" + std::to_string(row) + "] = 0.0;");
                    for (int col = 0; col < node->dense.cols; ++col) {
                        const double value = node->dense(row, col);
                        if (value != 0.0) {
                            context.writer->line(out + "[" + std::to_string(row) + "] += " + number_literal(value) + " * " + arg + "[" + std::to_string(col) + "];");
                        }
                    }
                }
                break;
            }
            case GraphNodeKind::SparseMatVec: {
                const std::string arg = emit_vec_temp(context, node->lhs, "smv");
                for (int i = 0; i < node->size; ++i) {
                    context.writer->line(out + "[" + std::to_string(i) + "] = 0.0;");
                }
                for (int k = 0; k < node->sparse.nnz(); ++k) {
                    const double value = node->sparse.values[static_cast<std::size_t>(k)];
                    if (value != 0.0) {
                        context.writer->line(out + "[" + std::to_string(node->sparse.row[static_cast<std::size_t>(k)]) + "] += " + number_literal(value) + " * " + arg + "[" + std::to_string(node->sparse.col[static_cast<std::size_t>(k)]) + "];");
                    }
                }
                break;
            }
            case GraphNodeKind::SymbolicMatVec: {
                const std::string matrix = emit_vec_temp(context, node->lhs, "symmv_a");
                const std::string rhs = emit_vec_temp(context, node->rhs, "symmv_x");
                for (int row = 0; row < node->mat_lhs_rows; ++row) {
                    context.writer->line(out + "[" + std::to_string(row) + "] = 0.0;");
                    for (int col = 0; col < node->mat_lhs_cols; ++col) {
                        const int matrix_index = detail::matrix_flat_index(row, col, node->mat_lhs_rows, node->mat_lhs_cols, node->mat_lhs_layout);
                        context.writer->line(out + "[" + std::to_string(row) + "] += " + matrix + "[" + std::to_string(matrix_index) + "] * " + rhs + "[" + std::to_string(col) + "];");
                    }
                }
                break;
            }
            case GraphNodeKind::SymbolicMatMul: {
                const std::string lhs = emit_vec_temp(context, node->lhs, "symmm_l");
                const std::string rhs = emit_vec_temp(context, node->rhs, "symmm_r");
                for (int row = 0; row < node->mat_lhs_rows; ++row) {
                    for (int col = 0; col < node->mat_rhs_cols; ++col) {
                        const int output_index = detail::matrix_flat_index(row, col, node->mat_lhs_rows, node->mat_rhs_cols, node->mat_result_layout);
                        context.writer->line(out + "[" + std::to_string(output_index) + "] = 0.0;");
                        for (int inner = 0; inner < node->mat_lhs_cols; ++inner) {
                            const int lhs_index = detail::matrix_flat_index(row, inner, node->mat_lhs_rows, node->mat_lhs_cols, node->mat_lhs_layout);
                            const int rhs_index = detail::matrix_flat_index(inner, col, node->mat_rhs_rows, node->mat_rhs_cols, node->mat_rhs_layout);
                            context.writer->line(out + "[" + std::to_string(output_index) + "] += " + lhs + "[" + std::to_string(lhs_index) + "] * " + rhs + "[" + std::to_string(rhs_index) + "];");
                        }
                    }
                }
                break;
            }
            case GraphNodeKind::SymbolicSparseMatVec: {
                const std::string values = emit_vec_temp(context, node->lhs, "symsmv_a");
                const std::string rhs = emit_vec_temp(context, node->rhs, "symsmv_x");
                for (int i = 0; i < node->size; ++i) {
                    context.writer->line(out + "[" + std::to_string(i) + "] = 0.0;");
                }
                for (int k = 0; k < node->sparse.nnz(); ++k) {
                    context.writer->line(out + "[" + std::to_string(node->sparse.row[static_cast<std::size_t>(k)]) + "] += " +
                                         values + "[" + std::to_string(k) + "] * " +
                                         rhs + "[" + std::to_string(node->sparse.col[static_cast<std::size_t>(k)]) + "];");
                }
                break;
            }
            case GraphNodeKind::SymbolicSparseMatMul: {
                const std::string lhs = emit_vec_temp(context, node->lhs, "symsmm_l");
                const std::string rhs = emit_vec_temp(context, node->rhs, "symsmm_r");
                for (int i = 0; i < node->size; ++i) {
                    context.writer->line(out + "[" + std::to_string(i) + "] = 0.0;");
                }
                if (node->symbolic_sparse_lhs) {
                    for (int k = 0; k < node->sparse.nnz(); ++k) {
                        const int row = node->sparse.row[static_cast<std::size_t>(k)];
                        const int inner = node->sparse.col[static_cast<std::size_t>(k)];
                        for (int col = 0; col < node->mat_rhs_cols; ++col) {
                            const int output_index = detail::matrix_flat_index(row, col, node->mat_lhs_rows, node->mat_rhs_cols, node->mat_result_layout);
                            const int dense_index = detail::matrix_flat_index(inner, col, node->mat_rhs_rows, node->mat_rhs_cols, node->mat_rhs_layout);
                            context.writer->line(out + "[" + std::to_string(output_index) + "] += " +
                                                 lhs + "[" + std::to_string(k) + "] * " +
                                                 rhs + "[" + std::to_string(dense_index) + "];");
                        }
                    }
                } else {
                    for (int row = 0; row < node->mat_lhs_rows; ++row) {
                        for (int k = 0; k < node->sparse.nnz(); ++k) {
                            const int inner = node->sparse.row[static_cast<std::size_t>(k)];
                            const int col = node->sparse.col[static_cast<std::size_t>(k)];
                            const int output_index = detail::matrix_flat_index(row, col, node->mat_lhs_rows, node->mat_rhs_cols, node->mat_result_layout);
                            const int dense_index = detail::matrix_flat_index(row, inner, node->mat_lhs_rows, node->mat_lhs_cols, node->mat_lhs_layout);
                            context.writer->line(out + "[" + std::to_string(output_index) + "] += " +
                                                 lhs + "[" + std::to_string(dense_index) + "] * " +
                                                 rhs + "[" + std::to_string(k) + "];");
                        }
                    }
                }
                break;
            }
            case GraphNodeKind::OuterProduct: {
                const std::string lhs = emit_vec_temp(context, node->lhs, "outer_l");
                const std::string rhs = emit_vec_temp(context, node->rhs, "outer_r");
                for (int row = 0; row < node->mat_lhs_rows; ++row) {
                    for (int col = 0; col < node->mat_rhs_cols; ++col) {
                        const int output_index = detail::matrix_flat_index(row, col, node->mat_lhs_rows, node->mat_rhs_cols, node->mat_result_layout);
                        context.writer->line(out + "[" + std::to_string(output_index) + "] = " + lhs + "[" + std::to_string(row) + "] * " + rhs + "[" + std::to_string(col) + "];");
                    }
                }
                break;
            }
            case GraphNodeKind::LinearSolve: {
                if (options_.scalar_type != "double") {
                    throw std::runtime_error("linear solve codegen currently requires double scalar_type");
                }
                const int n = node->mat_lhs_rows;
                const std::string matrix = emit_vec_temp(context, node->lhs, "lins_a_src");
                const std::string rhs = emit_vec_temp(context, node->rhs, "lins_b_src");
                const std::string problem = context.new_temp("lins_problem");
                const int layout = node->mat_lhs_layout == MatrixLayout::ColumnMajor ? 0 : 1;
                const int transpose = node->linear_solve_transpose ? 1 : 0;
                context.writer->line("MOOAdLinearSolveProblem " + problem + " = {" +
                                      std::to_string(n) + ", " +
                                      std::to_string(layout) + ", " +
                                      std::to_string(transpose) + ", " +
                                      matrix + ", " +
                                      rhs + ", " +
                                      out + "};");
                context.writer->line("if (" + options_.linear_solve_function + "(&" + problem + ") != 0) {");
                context.writer->indent();
                context.writer->line("for (int i = 0; i < " + std::to_string(n) + "; ++i) { " + out + "[i] = NAN; }");
                context.writer->dedent();
                context.writer->line("}");
                break;
            }
            case GraphNodeKind::Slice: {
                const std::string arg = emit_vec_temp(context, node->lhs, "sl");
                for (int i = 0; i < node->size; ++i) {
                    context.writer->line(out + "[" + std::to_string(i) + "] = " + arg + "[" + std::to_string(node->start + i) + "];");
                }
                break;
            }
            case GraphNodeKind::ScatterSlice: {
                for (int i = 0; i < node->size; ++i) {
                    context.writer->line(out + "[" + std::to_string(i) + "] = 0.0;");
                }
                const std::string arg = emit_vec_temp(context, node->lhs, "ss");
                for (int i = 0; i < node->lhs->size; ++i) {
                    context.writer->line(out + "[" + std::to_string(node->start + i) + "] = " + arg + "[" + std::to_string(i) + "];");
                }
                break;
            }
            case GraphNodeKind::Gather: {
                const std::string arg = emit_vec_temp(context, node->lhs, "g");
                for (int i = 0; i < node->size; ++i) {
                    context.writer->line(out + "[" + std::to_string(i) + "] = " + arg + "[" + std::to_string(node->indices[static_cast<std::size_t>(i)]) + "];");
                }
                break;
            }
            case GraphNodeKind::ScatterAdd: {
                for (int i = 0; i < node->size; ++i) {
                    context.writer->line(out + "[" + std::to_string(i) + "] = 0.0;");
                }
                const std::string arg = emit_vec_temp(context, node->lhs, "sa");
                for (int i = 0; i < node->lhs->size; ++i) {
                    context.writer->line(out + "[" + std::to_string(node->indices[static_cast<std::size_t>(i)]) + "] += " + arg + "[" + std::to_string(i) + "];");
                }
                break;
            }
            case GraphNodeKind::Concat:
                emit_vec_to(context, node->lhs, out);
                {
                    const std::string rhs = emit_vec_temp(context, node->rhs, "cat");
                    for (int i = 0; i < node->rhs->size; ++i) {
                        context.writer->line(out + "[" + std::to_string(node->lhs->size + i) + "] = " + rhs + "[" + std::to_string(i) + "];");
                    }
                }
                break;
            case GraphNodeKind::FunctionCall:
                emit_function_call(context, node, out);
                break;
            case GraphNodeKind::MappedFunctionCall:
                emit_mapped_call(context, node, out);
                break;
            case GraphNodeKind::MapAccumCall:
                emit_map_accum_call(context, node, out);
                break;
            default:
                throw std::runtime_error("unsupported vector node in codegen");
        }
    }

    std::string emit_callee_params(EmitContext &context, const FunctionCore &callee) {
        if (callee.parameters.size() == 0) {
            return "0";
        }
        const std::string callee_params = declare_array(context, callee.parameters.size(), "cp");
        for (int i = 0; i < callee.parameters.size(); ++i) {
            const int source = require_param_index(context, callee.parameters[i]);
            context.writer->line(callee_params + "[" + std::to_string(i) + "] = p[" + std::to_string(source) + "];");
        }
        return callee_params;
    }

    void emit_function_call(EmitContext &context, const std::shared_ptr<const VecNode> &node, const std::string &out) {
        if (!node->function) {
            throw std::runtime_error("function call node is missing callee in codegen");
        }
        const FunctionCore &callee = *node->function;
        const std::string input = declare_array(context, callee.info.input_size, "f_in");
        int offset = 0;
        for (std::size_t i = 0; i < node->arguments.size(); ++i) {
            const int size = callee.info.inputs[i].size;
            const std::string arg = emit_vec_temp(context, node->arguments[i], "arg");
            for (int j = 0; j < size; ++j) {
                context.writer->line(input + "[" + std::to_string(offset + j) + "] = " + arg + "[" + std::to_string(j) + "];");
            }
            offset += size;
        }
        const std::string callee_params = emit_callee_params(context, callee);
        context.writer->line(function_name(&callee) + "(" + input + ", " + callee_params + ", " + out + ");");
    }

    std::string mapped_index_expr(EmitContext &context,
                                  const detail::MappedBindingNode &binding,
                                  int reps,
                                  const std::string &rep,
                                  const std::string &component) {
        switch (binding.map_kind) {
            case MapKind::Blocks:
                return "((" + rep + ") * " + std::to_string(binding.local_size) + " + (" + component + "))";
            case MapKind::ShiftedBlocks:
                return "(((" + rep + ") + " + std::to_string(binding.shift) + ") * " + std::to_string(binding.local_size) + " + (" + component + "))";
            case MapKind::Stride:
                return "(" + std::to_string(binding.base) + " + (" + rep + ") * " + std::to_string(binding.rep_stride) + " + (" + component + ") * " + std::to_string(binding.component_stride) + ")";
            case MapKind::Stencil: {
                const std::string offsets = declare_int_array(context, binding.offsets, "offsets");
                return "(" + std::to_string(binding.base) + " + (" + rep + ") * " + std::to_string(binding.rep_stride) + " + " + offsets + "[" + component + "])";
            }
            case MapKind::Single:
            case MapKind::ExplicitIndices:
            case MapKind::Table: {
                const std::string table = declare_int_array(context, binding.indices, "mapidx");
                return table + "[((" + rep + ") * " + std::to_string(binding.local_size) + ") + (" + component + ")]";
            }
            case MapKind::Invalid:
                break;
        }
        (void)reps;
        throw std::runtime_error("invalid map kind in codegen");
    }

    void emit_mapped_call(EmitContext &context, const std::shared_ptr<const VecNode> &node, const std::string &out) {
        if (!node->function) {
            throw std::runtime_error("mapped function call node is missing callee in codegen");
        }
        const FunctionCore &callee = *node->function;
        const int local_output_size = callee.info.output_size;
        const std::string callee_params = emit_callee_params(context, callee);

        std::vector<std::string> source_names;
        source_names.reserve(node->mapped_bindings.size());
        for (const auto &binding : node->mapped_bindings) {
            source_names.push_back(emit_vec_temp(context, binding.source, "src"));
        }

        const std::string local_input = declare_array(context, callee.info.input_size, "local_in");
        std::string local_output;
        if (node->mapped_output.mode() != OutputMode::Concat) {
            local_output = declare_array(context, local_output_size, "local_out");
            for (int i = 0; i < node->size; ++i) {
                context.writer->line(out + "[" + std::to_string(i) + "] = 0.0;");
            }
        }

        std::string scatter_indices;
        std::string weights;
        if (node->mapped_output.mode() == OutputMode::Scatter) {
            scatter_indices = declare_int_array(context, node->mapped_output.indices(), "outidx");
        } else if (node->mapped_output.mode() == OutputMode::WeightedSum) {
            weights = declare_scalar_array(context, node->mapped_output.weights(), "weights");
        }

        context.writer->line("for (int rep = 0; rep < " + std::to_string(node->reps) + "; ++rep) {");
        context.writer->indent();
        int offset = 0;
        for (std::size_t binding_index = 0; binding_index < node->mapped_bindings.size(); ++binding_index) {
            const detail::MappedBindingNode &binding = node->mapped_bindings[binding_index];
            context.writer->line("for (int component = 0; component < " + std::to_string(binding.local_size) + "; ++component) {");
            context.writer->indent();
            const std::string source_index = mapped_index_expr(context, binding, node->reps, "rep", "component");
            context.writer->line(local_input + "[" + std::to_string(offset) + " + component] = " + source_names[binding_index] + "[" + source_index + "];");
            context.writer->dedent();
            context.writer->line("}");
            offset += binding.local_size;
        }

        if (node->mapped_output.mode() == OutputMode::Concat) {
            context.writer->line(function_name(&callee) + "(" + local_input + ", " + callee_params + ", " + out + " + rep * " + std::to_string(local_output_size) + ");");
        } else {
            context.writer->line(function_name(&callee) + "(" + local_input + ", " + callee_params + ", " + local_output + ");");
            context.writer->line("for (int row = 0; row < " + std::to_string(local_output_size) + "; ++row) {");
            context.writer->indent();
            if (node->mapped_output.mode() == OutputMode::Scatter) {
                context.writer->line(out + "[" + scatter_indices + "[rep * " + std::to_string(local_output_size) + " + row]] += " + local_output + "[row];");
            } else if (node->mapped_output.mode() == OutputMode::Sum) {
                context.writer->line(out + "[row] += " + local_output + "[row];");
            } else if (node->mapped_output.mode() == OutputMode::WeightedSum) {
                context.writer->line(out + "[row] += " + weights + "[rep] * " + local_output + "[row];");
            }
            context.writer->dedent();
            context.writer->line("}");
        }
        context.writer->dedent();
        context.writer->line("}");
    }

    int map_accum_emit_offset(const FunctionCore &core, int reps, int output_index) {
        const int carry_size = core.info.outputs[0].size;
        int offset = carry_size + reps * carry_size;
        for (int i = 1; i < output_index; ++i) {
            offset += reps * core.info.outputs[static_cast<std::size_t>(i)].size;
        }
        return offset;
    }

    void emit_map_accum_call(EmitContext &context, const std::shared_ptr<const VecNode> &node, const std::string &out) {
        if (!node->function) {
            throw std::runtime_error("map-accum call node is missing callee in codegen");
        }
        if (node->carry_input_index < 0 || node->carry_input_index >= node->function->info.input_count) {
            throw std::runtime_error("map-accum call has invalid carry input index in codegen");
        }

        const FunctionCore &callee = *node->function;
        const int carry_size = callee.info.outputs[0].size;
        const int local_output_size = callee.info.output_size;
        const std::string callee_params = emit_callee_params(context, callee);

        std::vector<std::string> source_names;
        source_names.reserve(node->mapped_bindings.size());
        for (const auto &binding : node->mapped_bindings) {
            source_names.push_back(emit_vec_temp(context, binding.source, "acc_src"));
        }

        const std::string carry = declare_array(context, carry_size, "carry");
        const std::string next_carry = declare_array(context, carry_size, "next_carry");
        const std::string local_input = declare_array(context, callee.info.input_size, "acc_in");
        const std::string local_output = declare_array(context, local_output_size, "acc_out");
        emit_vec_to(context, node->lhs, carry);

        context.writer->line("for (int rep = 0; rep < " + std::to_string(node->reps) + "; ++rep) {");
        context.writer->indent();
        int input_offset = 0;
        std::size_t sequence_binding = 0;
        for (int input_index = 0; input_index < callee.info.input_count; ++input_index) {
            const int input_size = callee.info.inputs[static_cast<std::size_t>(input_index)].size;
            if (input_index == node->carry_input_index) {
                context.writer->line("for (int component = 0; component < " + std::to_string(input_size) + "; ++component) {");
                context.writer->indent();
                context.writer->line(local_input + "[" + std::to_string(input_offset) + " + component] = " + carry + "[component];");
                context.writer->dedent();
                context.writer->line("}");
            } else {
                const detail::MappedBindingNode &binding = node->mapped_bindings[sequence_binding];
                context.writer->line("for (int component = 0; component < " + std::to_string(input_size) + "; ++component) {");
                context.writer->indent();
                const std::string source_index = mapped_index_expr(context, binding, node->reps, "rep", "component");
                context.writer->line(local_input + "[" + std::to_string(input_offset) + " + component] = " + source_names[sequence_binding] + "[" + source_index + "];");
                context.writer->dedent();
                context.writer->line("}");
                ++sequence_binding;
            }
            input_offset += input_size;
        }

        context.writer->line(function_name(&callee) + "(" + local_input + ", " + callee_params + ", " + local_output + ");");
        const int local_carry_offset = callee.info.outputs[0].offset;
        for (int i = 0; i < carry_size; ++i) {
            context.writer->line(next_carry + "[" + std::to_string(i) + "] = " + local_output + "[" + std::to_string(local_carry_offset + i) + "];");
            context.writer->line(out + "[" + std::to_string(carry_size) + " + rep * " + std::to_string(carry_size) + " + " + std::to_string(i) + "] = " + next_carry + "[" + std::to_string(i) + "];");
        }
        for (int output_index = 1; output_index < callee.info.output_count; ++output_index) {
            const FunctionOutputInfo &output = callee.info.outputs[static_cast<std::size_t>(output_index)];
            const int target_offset = map_accum_emit_offset(callee, node->reps, output_index);
            for (int i = 0; i < output.size; ++i) {
                context.writer->line(out + "[" + std::to_string(target_offset) + " + rep * " + std::to_string(output.size) + " + " + std::to_string(i) + "] = " + local_output + "[" + std::to_string(output.offset + i) + "];");
            }
        }
        for (int i = 0; i < carry_size; ++i) {
            context.writer->line(carry + "[" + std::to_string(i) + "] = " + next_carry + "[" + std::to_string(i) + "];");
        }
        context.writer->dedent();
        context.writer->line("}");
        for (int i = 0; i < carry_size; ++i) {
            context.writer->line(out + "[" + std::to_string(i) + "] = " + carry + "[" + std::to_string(i) + "];");
        }
    }

    void emit_sparsity_metadata(Writer &w) {
        const SparsityPattern sp = detail::function_from_core(root_).jacobian_sparsity();
        w.line();
        w.line("int " + options_.function_name + "_jacobian_nnz(void) { return " + std::to_string(sp.nnz()) + "; }");
        w.line("void " + options_.function_name + "_jacobian_sparsity(int* rows, int* cols) {");
        w.indent();
        int index = 0;
        for (const auto &entry : sp.entries()) {
            w.line("rows[" + std::to_string(index) + "] = " + std::to_string(entry.first) + "; cols[" + std::to_string(index) + "] = " + std::to_string(entry.second) + ";");
            ++index;
        }
        w.dedent();
        w.line("}");
    }
};

} // namespace

CodegenResult generate_c(const Function &function,
                         const CodegenOptions &options) {
    return Codegen(function, options).generate();
}

} // namespace ad
