name: Build

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        generator: ["Ninja", "Makefiles"] # Makefiles expands to Unix or MSYS Makefiles
        compiler-pair:
          - { c: "gcc", cxx: "g++" , fortran: "gfortran"}
          - { c: "clang", cxx: "clang++" , fortran: "gfortran"} # flang-20 isnt available on 'Jammy'

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: "recursive"

      - name: Install Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -qq
          sudo apt-get -qqy install libmetis-dev liblapack-dev gfortran make ninja-build

      - name: Install Dependencies (Windows)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: |
            mingw-w64-ucrt-x86_64-metis
            mingw-w64-ucrt-x86_64-openblas
            mingw-w64-ucrt-x86_64-gcc-fortran
            mingw-w64-ucrt-x86_64-clang
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-ninja

      - name: Configure (Linux)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          METIS_LIB_PATH="/usr/lib/x86_64-linux-gnu/libmetis.so"
          METIS_INC_PATH="/usr/include"
          if [ "${{ matrix.generator }}" = "Makefiles" ]; then
            GENERATOR="Unix Makefiles"
          else
            GENERATOR="Ninja"
          fi

          cmake -S . -B build \
            -DCMAKE_INSTALL_PREFIX=install \
            -DCMAKE_C_COMPILER=${{ matrix.compiler-pair.c }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.compiler-pair.cxx }} \
            -DCMAKE_Fortran_COMPILER=${{ matrix.compiler-pair.fortran }} \
            -DMETIS_LIB_PATH=${METIS_LIB_PATH} \
            -DMETIS_INC_PATH=${METIS_INC_PATH} \
            -DMOO_WITH_GDOPT_EXAMPLE=ON \
            -G "${GENERATOR}"

      - name: Configure (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          export PATH="/ucrt64/bin:$PATH"
          METIS_LIB_PATH="/ucrt64/bin/libmetis.dll"
          METIS_INC_PATH="/ucrt64/include"
          if [ "${{ matrix.generator }}" = "Makefiles" ]; then
            GENERATOR="MSYS Makefiles"
          else
            GENERATOR="Ninja"
          fi

          cmake -S . -B build \
            -DCMAKE_INSTALL_PREFIX=install \
            -DCMAKE_C_COMPILER=${{ matrix.compiler-pair.c }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.compiler-pair.cxx }} \
            -DCMAKE_Fortran_COMPILER=${{ matrix.compiler-pair.fortran }} \
            -DMETIS_LIB_PATH=${METIS_LIB_PATH} \
            -DMETIS_INC_PATH=${METIS_INC_PATH} \
            -DMOO_WITH_GDOPT_EXAMPLE=ON \
            -G "${GENERATOR}"

      - name: Build (Linux)
        if: runner.os == 'Linux'
        shell: bash
        run: cmake --build build --target install -- -j$(nproc)

      - name: Build (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: cmake --build build --target install -- -j$(nproc)

      - name: Run test (Linux)
        if: runner.os == 'Linux'
        shell: bash
        run: ./build/gdopt

      - name: Run test (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: ./build/gdopt

      - uses: actions/upload-artifact@v4
        with:
          name: install-${{ matrix.os }}-${{ matrix.generator }}-${{ matrix.compiler-pair.c }}
          path: install/
