name: Build

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        setup:
          - { c: "gcc",   cxx: "g++",     fortran: "gfortran", generator: "Unix Makefiles" }
          - { c: "clang", cxx: "clang++", fortran: "gfortran", generator: "Ninja"}

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get -qqy install libmetis-dev liblapack-dev gfortran

      - name: Configure
        run: |
          cmake -S . -B build \
            -DCMAKE_INSTALL_PREFIX=install \
            -DCMAKE_C_COMPILER=${{ matrix.setup.c }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.setup.cxx }} \
            -DCMAKE_Fortran_COMPILER=${{ matrix.setup.fortran }} \
            -DMOO_WITH_GDOPT_EXAMPLE=ON \
            -G "${{ matrix.setup.generator }}"

      - name: Build
        run: cmake --build build --target install -- -j$(nproc)

      - name: Run test
        run: ./build/gdopt

      - uses: actions/upload-artifact@v4
        with:
          name: install-linux-${{ matrix.setup.c }}-${{ matrix.setup.generator }}
          path: install/

  build-windows:
    timeout-minutes: 30
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        setup:
          - { c: "gcc", cxx: "g++", fortran: "gfortran", generator: "MSYS Makefiles" }

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install Dependencies
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: |
            mingw-w64-ucrt-x86_64-metis
            mingw-w64-ucrt-x86_64-openblas
            mingw-w64-ucrt-x86_64-gcc-fortran
            mingw-w64-ucrt-x86_64-clang
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-ninja
            make

      - name: Configure
        shell: msys2 {0}
        run: |
          export PATH="/ucrt64/bin:$PATH"
          cmake -S . -B build \
            -DCMAKE_INSTALL_PREFIX=install \
            -DCMAKE_C_COMPILER=${{ matrix.setup.c }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.setup.cxx }} \
            -DCMAKE_Fortran_COMPILER=${{ matrix.setup.fortran }} \
            -DMOO_WITH_GDOPT_EXAMPLE=ON \
            -G "${{ matrix.setup.generator }}"

      - name: Build
        shell: msys2 {0}
        run: cmake --build build --target install -- -j$(nproc)

      - name: Run test
        shell: msys2 {0}
        run: ./build/gdopt

      - uses: actions/upload-artifact@v4
        with:
          name: install-windows-${{ matrix.setup.c }}-${{ matrix.setup.generator }}
          path: install/

  build-macos:
    timeout-minutes: 30
    runs-on: macos-latest
    strategy:
      fail-fast: true
      matrix:
        setup:
          - { c: "clang", cxx: "clang++", fortran: "gfortran-15", generator: "Ninja" }

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          brew update
          brew install metis

      - name: Configure
        run: |
          cmake -S . -B build \
            -DCMAKE_INSTALL_PREFIX=install \
            -DCMAKE_C_COMPILER=${{ matrix.setup.c }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.setup.cxx }} \
            -DCMAKE_Fortran_COMPILER=${{ matrix.setup.fortran }} \
            -DMOO_WITH_GDOPT_EXAMPLE=ON \
            -G "${{ matrix.setup.generator }}"

      - name: Build
        run: cmake --build build --target install -- -j$(sysctl -n hw.logicalcpu)

      - name: Run test
        run: ./build/gdopt

      - uses: actions/upload-artifact@v4
        with:
          name: install-macos-${{ matrix.setup.c }}-${{ matrix.setup.generator }}
          path: install/
